# Generated by Django 4.2.5 on 2023-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateregistration',
            name='profile_image',
            field=models.ImageField(default='SystemUser/assets/dist/img/default.jpeg', upload_to='SystemUser/assets/dist/img'),
        ),
    ]
