# Generated by Django 4.2.5 on 2023-09-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemUser', '0002_candidateregistration_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateregistration',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='email',
            field=models.EmailField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='first_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='id_number',
            field=models.CharField(default=-1, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='last_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='password',
            field=models.CharField(default='ajay', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='phone',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='reg_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
