# Generated by Django 4.2.5 on 2023-09-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemUser', '0003_alter_candidateregistration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateregistration',
            name='profile_image',
            field=models.ImageField(default='SystemUser/assets/dist/img/default.jpeg', upload_to='SystemUser/assets/dist/img/'),
        ),
    ]
