# Generated by Django 4.2.5 on 2023-09-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemUser', '0007_alter_candidateregistration_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateregistration',
            name='profile_image',
            field=models.ImageField(default=None, null=True, upload_to='uploaded_image/'),
        ),
    ]
